name: Django backend tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  generate-matrix:
    name: Generate test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Clone test suite
        uses: actions/checkout@v4
        with:
          repository: singlestore-labs/django
          ref: singlestore-test-4.2.x
          path: testrepo

      - name: Generate matrix JSON
        id: set-matrix
        run: |
          python scripts/get_test_matrix.py testrepo/tests | tee matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  run-tests:
    name: Run tests (Group ${{ matrix.group }})
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
        matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    services:
      singlestore:
        image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
        ports:
          - 3306:3306
          - 8080:8080
          - 9000:9000
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "p"
      
    steps:
      - name: Checkout django-singlestore repo
        uses: actions/checkout@v4

      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          repository: singlestore-labs/django
          ref: singlestore-test-4.2.x
          path: testrepo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          pip install ./testrepo
          pip install .

      - name: Run setup script
        run: |
          echo "Running setup script for group ${{ matrix.group }}"
          python scripts/setup_group.py ${{ matrix.group }}

      - name: Run test modules for group
        run: |
          echo "Running test modules for group ${{ matrix.group }}"
          python scripts/run_group.py '${{ toJson(matrix.modules) }}'

