name: Django backend tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  generate-matrix:
    name: Generate test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Clone test suite
        uses: actions/checkout@v4
        with:
          repository: singlestore-labs/django
          ref: singlestore-test-4.2.x
          path: testrepo

      - name: Generate matrix JSON
        id: set-matrix
        run: |
          python scripts/get_test_matrix.py testrepo/tests > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  run-tests:
    name: Run tests (Group ${{ matrix.group }})
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [0, 1, 2, 3, 4]
    services:
      singlestore:
        image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
        ports:
          - 3307:3306
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: root
        # options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout django-singlestore repo
        uses: actions/checkout@v4

      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          repository: singlestore-labs/django
          ref: singlestore-test-4.2.x
          path: testrepo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Export env vars from local_test.sh
        run: |
          set -a
          source testrepo/tests/_utils/local_test.sh
          set +a

      - name: Run setup script
        run: |
          echo "Running setup script for group ${{ matrix.group }}"
          python scripts/setup_group.py ${{ matrix.group }}
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}

      - name: Run test modules for group
        run: |
          echo "Running test modules for group ${{ matrix.group }}"
          python scripts/run_group.py ${{ matrix.group }}
        env:
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
